#!/usr/bin/env bash
# Guards the release manifest: the committed release-manifest.json must
# be what the generator produces from this tree.
#
# A consumer taking a new revision has to re-pin what this repository
# holds down. CHANGELOG.md names five of those values in prose, which a
# person can read and a consumer's CI cannot diff; the manifest is the
# machine-readable form of eight, generated by `cargo xtask
# gen-release-manifest` from the definitions that own them. The two are
# not independent claims — both are checked against the same tree.
#
# The check regenerates into a temporary file and compares. It never
# rewrites the committed manifest: a guard that repaired the drift it
# exists to report would turn a hand-edited pin into a silent pass.
#
# Two things this deliberately does NOT prove:
#
#   - That a consumer's pins are current. This file states what this
#     revision pins; comparing it against a consumer's own pinned values
#     is a check that belongs in the consumer's repository, written
#     against this file.
#   - That a moved value was released. The comparison is
#     manifest-against-tree, so moving a pin and regenerating together
#     passes, exactly as the changelog guard does. Cutting a release for
#     a moved value is review's job (CONTRIBUTING.md).
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

manifest="${INDICATE_RELEASE_MANIFEST:-release-manifest.json}"
# The generator's package, so the selftest can prove this fails closed
# when generation fails at all rather than only when the output differs.
generator_package="${INDICATE_MANIFEST_GENERATOR_PACKAGE:-xtask}"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

fail_closed() {
    echo "$1" >&2
    echo "check-release-manifest: FAILED" >&2
    exit 1
}

[ -f "$manifest" ] || fail_closed "MISSING MANIFEST: $manifest does not exist (fail-closed); run: cargo run -q -p xtask -- gen-release-manifest"
[ -s "$manifest" ] || fail_closed "EMPTY MANIFEST: $manifest states no pinned values (fail-closed)"

generated="$tmp_dir/release-manifest.json"
if ! cargo run --locked -q -p "$generator_package" -- \
        gen-release-manifest --out "$generated" > "$tmp_dir/generator.log" 2>&1; then
    sed 's/^/    /' "$tmp_dir/generator.log" >&2
    fail_closed "GENERATOR FAILED: the manifest could not be regenerated, so $manifest cannot be vouched for (fail-closed)"
fi
[ -s "$generated" ] || fail_closed "GENERATOR PRODUCED NOTHING: $generated is empty (fail-closed)"

# Labelled, so the diff reads as committed-versus-tree rather than
# naming a temporary file the author cannot look at.
if ! diff -u -L "$manifest (committed)" -L "$manifest (what this tree generates)" \
        "$manifest" "$generated" > "$tmp_dir/diff" 2>&1; then
    # Name the keys that moved before showing the diff: the reader wants
    # to know which pin changed, not to read JSON for it.
    # A changed line naming no key is possible, so the summary is allowed
    # to come back empty rather than taking the run down with it: the
    # diff below is the answer either way.
    keys="$(grep -E '^[-+]' "$tmp_dir/diff" \
        | grep -vE '^(---|\+\+\+)' \
        | grep -oE '"[A-Za-z0-9]+":' \
        | tr -d '":' | sort -u | tr '\n' ' ' || true)"
    echo "DRIFT: $manifest disagrees with the tree it describes" >&2
    if [ -n "$keys" ]; then
        echo "DRIFT: the keys that moved: $keys" >&2
    fi
    sed 's/^/    /' "$tmp_dir/diff" >&2
    fail_closed "regenerate and commit it: cargo run -q -p xtask -- gen-release-manifest"
fi

# The tier law's selftest pattern: the guard ships with the proof that it
# fails on the modes it claims to catch, and one CI step runs both. The
# child guard stops the recursion, since the selftest runs this script.
if [ "${INDICATE_RELEASE_MANIFEST_SELFTEST_CHILD:-0}" != "1" ]; then
    if ! INDICATE_RELEASE_MANIFEST_SELFTEST_CHILD=1 bash "$root_dir/scripts/test-release-manifest.sh"; then
        echo "check-release-manifest: FAILED" >&2
        exit 1
    fi
fi

echo "check-release-manifest: OK ($manifest is what the generator produces from this tree)"
echo "check-release-manifest: states this revision's pins; a consumer's own pins are the consumer's check to write"
